-- MySQL Script generated by MySQL Workbench
-- Wed Oct 26 09:39:51 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Administrador` (
  `matricula` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `login` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`matricula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cartaz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cartaz` (
  `idCartaz` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL,
  `texto` VARCHAR(300) NULL,
  `anexo` VARCHAR(45) NULL,
  `data` DATE NULL,
  `hora` TIME(10) NULL,
  `Administrador_matricula` INT NOT NULL,
  PRIMARY KEY (`idCartaz`, `Administrador_matricula`),
  INDEX `fk_Cartaz_Administrador_idx` (`Administrador_matricula` ASC),
  CONSTRAINT `fk_Cartaz_Administrador`
    FOREIGN KEY (`Administrador_matricula`)
    REFERENCES `mydb`.`Administrador` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`palavraChave`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`palavraChave` (
  `idpalavraChave` INT NOT NULL AUTO_INCREMENT,
  `palavras` VARCHAR(100) NULL,
  PRIMARY KEY (`idpalavraChave`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `login` VARCHAR(45) NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`palavraChave_has_Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`palavraChave_has_Usuario` (
  `palavraChave_idpalavraChave` INT NOT NULL,
  `Usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`palavraChave_idpalavraChave`, `Usuario_idusuario`),
  INDEX `fk_palavraChave_has_Usuario_Usuario1_idx` (`Usuario_idusuario` ASC),
  INDEX `fk_palavraChave_has_Usuario_palavraChave1_idx` (`palavraChave_idpalavraChave` ASC),
  CONSTRAINT `fk_palavraChave_has_Usuario_palavraChave1`
    FOREIGN KEY (`palavraChave_idpalavraChave`)
    REFERENCES `mydb`.`palavraChave` (`idpalavraChave`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_palavraChave_has_Usuario_Usuario1`
    FOREIGN KEY (`Usuario_idusuario`)
    REFERENCES `mydb`.`Usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`palavraChave_has_Cartaz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`palavraChave_has_Cartaz` (
  `palavraChave_idpalavraChave` INT NOT NULL,
  `Cartaz_idCartaz` INT NOT NULL,
  `Cartaz_Administrador_matricula` INT NOT NULL,
  PRIMARY KEY (`palavraChave_idpalavraChave`, `Cartaz_idCartaz`, `Cartaz_Administrador_matricula`),
  INDEX `fk_palavraChave_has_Cartaz_Cartaz1_idx` (`Cartaz_idCartaz` ASC, `Cartaz_Administrador_matricula` ASC),
  INDEX `fk_palavraChave_has_Cartaz_palavraChave1_idx` (`palavraChave_idpalavraChave` ASC),
  CONSTRAINT `fk_palavraChave_has_Cartaz_palavraChave1`
    FOREIGN KEY (`palavraChave_idpalavraChave`)
    REFERENCES `mydb`.`palavraChave` (`idpalavraChave`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_palavraChave_has_Cartaz_Cartaz1`
    FOREIGN KEY (`Cartaz_idCartaz` , `Cartaz_Administrador_matricula`)
    REFERENCES `mydb`.`Cartaz` (`idCartaz` , `Administrador_matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
